# Generated by Django 4.2.3 on 2023-07-18 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(max_length=50)),
                ('product_brand', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=200)),
                ('product_image', models.CharField(max_length=300)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('product_description', models.CharField(blank=True, max_length=500, null=True)),
                ('product_rating', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
            ],
        ),
    ]
